### PR TITLE
removed and inserted options instead of disabling and enabling them

### PR DESCRIPTION
**Pull request by amirmahdifard**
i have tested and made sure i have developed everything properly, and everything works such as connecting to a untrusted fingre print promped, interupted connection, connected as master, connected as controled computer, and disconnection, also, i made sure all options and stuf works as expected, and they should, because i didn't tuch anything: you can build and try it and read the code, and if anything more you wish, you can let me know. Thanks!

### CODE REVIEW

**Comment by amirmahdifard** [comment]
this fixes https://github.com/nvda-es/TeleNVDA/issues/19

**Comment by amirmahdifard** [comment]
@jmdaweb hi: please look at this and confurm it or if there is anything needed, i can add, but as i tested, this is absolutely complete: thanks! this is my first contribution here

**Comment by amirmahdifard** [comment]
note that i didn't tuch coppy link sub menu and it's contaning options, because that was needed more work and they were not much, so i decided to keep  those as before only.

**Comment by amirmahdifard** [comment]
@jmdaweb are you activ? can you please see this? thanks

**Comment by amirmahdifard** [comment]
@tech10
@davidacm
hello, i'm really sorry, but can you also try this and confurm, i spent a lot of time implementing this even at my mid night, but the contributor didn't see it and anyone haven't looked at this at all: can you please help? i'm afrade: thanks a lot!

**Comment by jmdaweb** [comment]
Hi Amir,
Thanks for your contribution. I expect reviewing your changes this afternoon. For now, I'd like to provide some feedback, not exactly related to code, but related to behaviour and spelling. Many people complain about some things you do on other groups and projects, and I won't consent that here:

1. On issue #19, there are good reasons against this implementation and the discussion results aren't clear. See @bingen13 comment, for example. Spend time coding only if you are really sure your pr will be merged. Otherwise, you may get frustrated.
2. I have a job and a life. That means I need some free time to review the code and test the changes.
3. Related to previous point: I'm an human and not a machine. I won't answer instantly. In fact, if you flood my inbox and all issues with lots of comments, I will forget to answer for a long long time.
4. Confirm: c, o, n, f, i, r, m.
5. Afraid: a, f, r, a, i, d.
6. Fingerprint. Everything together, without spaces: f, i, n, g, e, r, p, r, i, n, t.
7. Better: b, e, t, t, e, r.
8. Touch: t, o, u, c, h.
9. Containing: c, o, n, t, a, i, n, i, n, g.
10. Active: a, c, t, i, v, e.

Regards.

**Comment by amirmahdifard** [comment]
@jmdaweb thanks if you review this.
i'm sorry about everything.
first, you said this suggestion is good, and i answered that person's comment. Not having unavailable options is very good, because,
1: it prevents a lot of options when they are useless, that is, they don't work because unavailable, just makes the menu harder to find the available options, and options are not always there
2: even in nvda it self, whenever they want to disable an option, they just remove it rather than making it unavailable, only nvda remote was like that and that was because the developers wasn't working on it.
3: that person mentioned about breaking the users expectations wich is not a good reason in my opinion, because even if they got used to this way, if they get the new way, i'm sure that they will get more happyor because first, they don't need to scrole down unavailable options as whell, second, this happened to me a lot, so users won't have the chance to by mistake klick on an unavailable option
please aply this and get feedback, i have no problem if later you revurted this change because people complaned about this, i'm sure people will like this more than the old way, because i also got feedback from lots of users before implementing this, and it is confirmed that it prevents user confusion, and speeding up users work as whel. Thanks a lot to you friend!

**Comment by amirmahdifard** [comment]
@jmdaweb
hello. I want to mention a fue things that are worth mentioning
firstly, i've seen that when others opened pull requests in this repo such as kary, you reviewed the changes in the same day and gave them a result. You mentioned about i have some things that annoys people in other projects or groupes. Whel, i'm sometimes excited about the suggestions i give, or pull requests i open. I'm really excited for your review so if anything is rong wich is not at least in my end and a fue people i gave this releace to them so they can use it because they like this way, you can tell me so i can work on it, and stuf. So don't think i'm a bad person, or anything. Just i feal i;m difrent for you than others because of these.
you said i will review your changes after noon, but you stil haven't, please do this when possible for you.
and final, i didn't comment this just to mention these. I see some bugs in tele nvda that are unrelated to this pr, they are small bugs, and i'd like to fix them my self to be help for the developers. I just want to ask can i fix them in this pr, or i need to open another pr for them? the bugs are:
1: the (Mute speech and sounds from the remote computer) and (Unmute speech and sounds from the remote computer) speach only announced if we use the mute gesture, when we klick on the mute / unmute option in the menu, this speach doesn't announced
2: when we are connected as slave, the mute gesture works and mutes and unmutes, wich shouldn't work, as the option is unavailable in this case because the mute function in slave mode doesn't have any meaning
also, i would like to know do you want me to update the changelog as whel, or you wish to do that yourself?
thanks, i'll be waiting for your answer because i want to know my way.

**Comment by ramoncorominas** [comment]
Hi Amir,

I understand your excitement, but please relax and stop asking for immediate review, that behavior is really aggressive and you will probably get exactly the opposite to what you want. If I were @jmdaweb I would probably have already closed your PR because you don't even take the time to pass a spell checker to your messages. If you don't care about the quality of your communication, why should anyone care about the rest of your work?

About the PR itself, you said:

> even in nvda itself, whenever they want to disable an option, they just remove it rather than making it unavailable

Well, if this is true I suppose that it will be easy for you to provide several examples of this behavior in the rest of NVDA, that would probably be more helpful than asking again and again to review your contribution.

Cheers!

**Comment by jmdaweb** [comment]
Hi Amir,
First of all, I'm sorry if I sounded a bit rude in my previous comment. Finally I have reviewed the code. It's a great work, but several community members have argued against the change with very good reasons and this pr won't be merged. Parallel conversations have taken place on mailing lists, Mastodon and other social networks and groups regarding this topic, including opinions from several UX experts.
Note that TeleNVDA is used by various users with different computing skills. On connections with high latency and other scenarios, pressing arrow keys a certain number of times is essential to perform an action without waiting for the speech response to arrive.
Also, from a coding perspective, WXPython doesn't allow showing or hiding menu items. They must be added and removed instead. We run into a risky situation where the items order may change after connecting, disconnecting or even reloading the add-on. This is definitely confusing for all users.
I'll pay attention to other problems you have described in your last comment. Having the mute remote item enabled on a slave session does not make sense, for example.
Regards, and thanks again for your effort.

**Pull request closed without merging**
