### PR TITLE
disable speech announcement for the muting except for using the shortcut

### PR DESCRIPTION
**Pull request by amirmahdifard**

### CODE REVIEW

**Comment by amirmahdifard** [comment]
i thort announcing speech is bettar, but it is not. for option we don't need speech because the lable gets changed anyway and we couldn't hear the speech until the end, and for this option it became annoying, so i limited it only to shortcut, like befor my pull request was called bug fixes for the mute flag

**Comment by jmdaweb** [comment]
Hi,
I need to review again the __init__.py file merged yesterday. I'll merge or close this pr tomorrow.

**Comment by amirmahdifard** [comment]
@jmdaweb hi, ok no problem, but if there were any bugs, don't fix it yourself, let me do it, i'm intrested.

**Comment by amirmahdifard** [comment]
@jmdaweb hi, i'm sorry to mention you again, but now it is 2 days passed from you said you'll review tomorro, and i want to ask you would you please have a look, i may be not be able to have access to a computer every day. Thanks.

**Comment by jmdaweb** [comment]
Hi,
Finally I have implemeted directly the solution.
Regards.

**Comment by amirmahdifard** [comment]
@jmdaweb hi bro, so bro, is all of my impelimentation is gon and it was useless? i'm really sad that my work didn't help you, i just wanted to contribute to this project and be useful for you, so i'm sad that my work was useless for you

**Pull request closed without merging**
